apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  annotations:
    #  # use-connector-resources configures this KafkaConnect
    #  # to use KafkaConnector resources to avoid
    #  # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
spec:
  version: 2.7.0
  replicas: 1
  build:
    output:
      type: docker
      image: image-registry.openshift-image-registry.svc:5000/myproject/connect-build:latest
    plugins:
      - name: gs-connector
        artifacts:
          - type: jar
            url: https://github.com/sknot-rh/google-sheet-source-connector/releases/download/0.0.9/google-sheet-source-connector-0.0.9.jar
            sha512sum: 1e8746d543a80957efd71f5cc4894c32ffb2c4b660a0fcb1c936561c9f878891a20c5aceb549927bb2ee1aca90410aab407cd9590d76e5bf3934f5f11d52b048
  bootstrapServers: my-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: my-cluster-cluster-ca-cert
        certificate: ca.crt
  externalConfiguration:
    volumes:
      - name: google-sheet-credentials
        secret:
          secretName: google-sheet-credentials
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    config.providers: directory
    config.providers.directory.class: org.apache.kafka.common.config.provider.DirectoryConfigProvider
  logging:
    type: inline
    loggers:
      log4j.rootLogger: "INFO"