apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: my-source-connector
  labels:
    # The strimzi.io/cluster label identifies the KafkaConnect instance
    # in which to create this connector. That KafkaConnect instance
    # must have the strimzi.io/use-connector-resources annotation
    # set to true.
    strimzi.io/cluster: my-connect-cluster
spec:
  class: GoogleSheetsSourceConnector
  tasksMax: 1
  config:
    spreadSheetId: 1A-RikPJcaC3L4-pkvYyPWp6z6g98NF0r1loYTdEmnYw
    accessToken: ${directory:/opt/kafka/external-configuration/google-sheet-credentials:google-sheet-credentials}
    range: A1:C3
    topics: my-google-sheet-topic
    delay: 3000